SHARED_CONF=/usr/share/config
source "$SHARED_CONF/zshconfig/base_config.zsh"
source "$SHARED_CONF/zshconfig/p10k/default_p10k.zsh"
source "$SHARED_CONF/zshconfig/fzf_config.zsh"
source "$SHARED_CONF/zshconfig/bat_config.zsh"
source "$SHARED_CONF/zshconfig/eza_config.zsh"
source "$SHARED_CONF/zshconfig/tf_config.zsh"
source "$SHARED_CONF/zshconfig/zoxide_config.zsh"
source "$SHARED_CONF/zshconfig/node_config.zsh"
source "$SHARED_CONF/zshconfig/docker_config.zsh"
source "$SHARED_CONF/zshconfig/dotnet_config.zsh"
source "$SHARED_CONF/zshconfig/wincopy_config.zsh"
source "$SHARED_CONF/zshconfig/custom_aliases.zsh"
source "$SHARED_CONF/zshconfig/cargo_config.zsh"
source "$SHARED_CONF/zshconfig/nvim_config.zsh"
